### ISSUE TITLE
Support the MediaRecorder API feature request on bugs.webkit.org

### ISSUE THREAD

**Issue by octavn** [ai/audio-recorder-polyfill#10]
This [bug report](https://bugs.webkit.org/show_bug.cgi?id=85851) on bugs.webkit.org tracks the MediaRecorder implementation in WebKit and thus Safari. 

I encourage everyone to show their interest and [add a comment](https://bugs.webkit.org/show_bug.cgi?id=85851) describing how a MediaRecorder implementation would help their project/development. Creating an account takes a second.

Chrome [implemented MediaRecorder in Jan 2016](https://developers.google.com/web/updates/2016/01/mediarecorder). By that time the MediaRecorder feature request had gathered [2800+ starts on bugs.chromium.org](https://bugs.chromium.org/p/chromium/issues/detail?id=113676).

Also, WebKit is an open source project so one can also contribute code towards implementing the MediaRecorder API.

**Comment by ai** [comment]
I added a comment :+1: 

Thanks for your passion and pushing Safari.
