### ISSUE TITLE
Problem with Safari 11 Mac OSX High Sierra

### ISSUE THREAD

**Issue by dirkk0** [ai/audio-recorder-polyfill#12]
Hi,

  I have a problem with the demo.
When I record something, most of the times (unfortunately not always) the first one or two seconds are clipped - meaning that after some silence the audio starts to play with a click. So if I record 'one two three' with a slow voice, I only hear ' ___ (click) two three'.

I wonder why that is?

Thanks, Dirk

**Comment by ai** [comment]
Seems like OS just have a lag during mic enabling. I don’t see a way to solve it.

**Comment by dirkk0** [comment]
No, this demo works fine, no trace of lag:
https://danielstorey.github.io/WebAudioTrack/index.html

**Comment by ai** [comment]
Good reason

**Comment by ai** [comment]
Unfortunately, I will not have time in the next few weeks (need a rest after conferences). Maybe somebody will investigate and send PR?

**Comment by ai** [comment]
Also I don’t have Mac to reproduce the error :(

**Comment by dirkk0** [comment]
My findings so far: this is a Safari/WebKit bug which I reported (here).[https://bugreport.apple.com/web/?problemID=42852112]
 
The other library has the same problem (a second of silence in the first recording, https://github.com/danielstorey/WebAudioTrack/issues/5 )

One possible workaround to mitigate this, is to make a short recording right a the start:
https://github.com/dirkk0/record-audio-webkit/blob/master/index.html#L47-L51

**Comment by ai** [comment]
@dirkk0 good research :+1: 

Should we do this quick recording in the library? Or  we just should recommend do it in app level in the docs?

**Comment by dirkk0** [comment]
For this particular problem, I would recommend app level.

**Comment by dirkk0** [comment]
Sorry for the long delay. Yes, I can do that.

**Comment by dirkk0** [comment]
I just checked my own demos - the bug seems to be gone, but my bug report on the Apple site is still open.
I'll check again in a week or two, and if it works then I'll close this issue as obsolete.

**Comment by nick96** [comment]
This bug seems to have come back as I've been running into it recently. Using Dirk's work around seems to fix it though. Unfortunately the bugreport link is dead as I guess Apple have moved to using other platforms.
