### ISSUE TITLE
Support `error` event type

### ISSUE THREAD

**Issue by tomquirk** [ai/audio-recorder-polyfill#13]
The standard MediaRecorder API specifies an `error` event:

> https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/onerror

I propose that `error` be added to the list of supported event types in order to more closely mirror the spec, and trigger it throughout to more consistently handle errors.

P.S fantastic work on this polyfill!!!!

**Comment by ai** [comment]
@tomquirk awesome idea. Do you want to send PR to save your name in the project history?

**Comment by tomquirk** [comment]
Yea absolutely @ai, I will get to it eventually!

**Comment by ai** [comment]
Released in 0.1.3
