### ISSUE TITLE
Conditionally importing for safari and edge

### ISSUE THREAD

**Issue by jrabello** [ai/audio-recorder-polyfill#16]
Hi, thanks for this very useful polyfil,

My question is: There is any way to avoid overidding the original MediaRecorder?

In my project It looks like something like:

```import * as MediaRecorderPoly from 'audio-recorder-polyfill';```

Still overrides it globally, and that kind of behaviour is what I wanted only safari and edge to do

**Comment by ai** [comment]
Yeap, just follow our install instructions

https://github.com/ai/audio-recorder-polyfill/blob/master/README.md#install

**Comment by jrabello** [comment]
Thanks!!!

**Comment by Nandhan-augment** [comment]
it supports angular 6 right?
