### ISSUE TITLE
Noise when recording voice in Safari browser

### ISSUE THREAD

**Issue by MarinescuEvghenii** [ai/audio-recorder-polyfill#17]
I'm able to record the audio in Safari Version 12.0 (13606.2.11) Mac OSX High Sierra, but the recorded sound is distorted. Here is the example https://goo.gl/2xY8tp. Do you know anything about this issue?

Thanks.

**Comment by ai** [comment]
Have no idea, sorry.

**Comment by harwee** [comment]
@MarinescuEvghenii were you able to solve this problem? I am facing the same.

**Comment by ai** [comment]
@harwee interesting. Can you make PR?

**Comment by nicolocarpignoli** [comment]
I can confirm that stream.clone() fix this

**Comment by ai** [comment]
@nicolocarpignoli do you want to send PR if you already changed the sources?

**Comment by harwee** [comment]
@ai  can you make a pull request, I tried making one but since i am not a JS developer I coudn't write test cases for this change 😞

**Comment by ai** [comment]
@harwee you can send PR without tests (it is OK for browser compatibility fixes)

**Comment by ai** [comment]
the fix released in 0.1.4
