### ISSUE TITLE
Firefox requesting permission

### ISSUE THREAD

**Issue by AsyncSan** [ai/audio-recorder-polyfill#20]
When you run the demo in Firefox, everytime you click on the record button you get asked for recoding permission.

I tried to load the:

```js
navigator.mediaDevices.getUserMedia({ audio: true }).then(stream => {
        recorder = new MediaRecorder(stream);
```

Once in the beginning, using reacts componentDidMount, but then the data wont be useable after the second recording.

Any workaround for this?

I understand that it need to be invoked because the `getUserMedia()` returns a stream object that needs to be passed in `.then()` but it doesn´t feel right.
In this Demo you are only prompted once (Tested on FF mobile) but the audio isn't recording
https://danielstorey.github.io/WebAudioTrack/index.html

**Comment by AsyncSan** [comment]
Thanks very much for the clarification.
But what do you think about:

**Comment by ai** [comment]
> But what do you think about the solution from

This solution is not good, since even if I clicked on “Stop recording”, Firefox will show me “recording is in the progress” notification overlay. It reduces trust to your website.

![ur0sfce](https://user-images.githubusercontent.com/19343/47608259-c7159f80-d9f8-11e8-9a65-94e25fb05436.png)

**Comment by ai** [comment]
Same in Chrome. Browser tab will continue to show “recording” icon even if I stopped recording.

![guctuxm](https://user-images.githubusercontent.com/19343/47608273-f6c4a780-d9f8-11e8-8312-13cfa5c0a04a.png)

**Comment by AsyncSan** [comment]
True, that is a valid argument
