### ISSUE TITLE
Not supported isTypeSupported method

### ISSUE THREAD

**Issue by floydback** [ai/audio-recorder-polyfill#21]
This is not working
`MediaRecorder.isTypeSupported(type)`

**Comment by ai** [comment]
It should work https://github.com/ai/audio-recorder-polyfill/blob/master/index.js#L244

What error do you have?

**Comment by mrowles** [comment]
I'm not sure if this is a bad test, but I've tried a bunch of them on Safari 12.0.1 (macOS Mojave) to no avail with a whole bunch of codecs:

```
    const codecs: string[] = [
      'video/webm;codecs=vp9',
      'video/webm;codecs=vp8',
      'video/webm',
      'video/webm;codecs=vp8.0',
      'video/webm;codecs=vp9.0',
      'video/webm;codecs=h264',
      'video/webm;codecs=H264',
      'video/webm;codecs=avc1',
      'video/webm;codecs=vp8,opus',
      'video/WEBM;codecs=VP8,OPUS',
      'video/webm;codecs=vp9,opus',
      'video/webm;codecs=vp8,vp9,opus',
      'video/webm;codecs=h264,opus',
      'video/webm;codecs=h264,vp9,opus',
      'video/x-matroska;codecs=avc1',
      'video/mp4',
      'video/3gpp',
      'video/3gpp2',
      'video/quicktime',
      'video/x-m4v'
    ];

    const options = {};

    for (const codec of codecs) {
      // @ts-ignore
      if (MediaRecorder.isTypeSupported(codec)) {
        console.log('found matching codec', codec);
        options['mimeType'] = codec;
        break;
      }
    }
```

I have a feeling that having no mimetype set is not letting me record on Safari, as the following handler never receives an event:

```
  record() {
    ...
    this.mediaRecorder.ondataavailable = this.handleDataAvailable.bind(this);
    ...
  }

  private handleDataAvailable(event) {
    console.log(event); // this never logs in Safari, goes nuts in Chrome, Firefox
    if (event.data && event.data.size > 0) {
      this.recordedBlobs.push(event.data);
    }
  }
```

**Comment by floydback** [comment]
In Chrome this work fine (without audio-recorder-polyfill)
```
MediaRecorder.isTypeSupported("audio/webm")
```

The problem appears when I start using audio-recorder-polyfill
```
import MediaRecorder from 'audio-recorder-polyfill'
window.MediaRecorder = MediaRecorder

MediaRecorder.isTypeSupported("audio/webm")
```
I believe `audio-recorder-polyfill` extend not replace native MediaRecorder object. I was wrong?

**Comment by ai** [comment]
This polyfill doesn’t support `audio/webm` (since webm encoder is huge). This polyfill convert audio only to `.wav` files. This is why it supports only `audio/wav` and `audio/wave` mime types. So polyfill result will be:

```js
import MediaRecorder from 'audio-recorder-polyfill'
window.MediaRecorder = MediaRecorder

MediaRecorder.isTypeSupported("audio/webm") //=> false, since polyfill doesn’t have webm encoder
MediaRecorder.isTypeSupported("audio/wav") //=> true, since it encodes to WAVE format
```

We have plans to add `ogg/vorbis` encoder to polyfill, but it still will not encode to `audio/webm` (WebM is not the best format right now, this is why it is better to support better Vorbis).

If you want to have WebM support, you can use [custom encoder](https://github.com/ai/audio-recorder-polyfill#custom-encoder):

```js
MediaRecorder.encoder = require('./webm-encoder')
MediaRecorder.mimeType = 'audio/webm'
```

Is this behavior sounds reasonable for you?

**Comment by floydback** [comment]
Thank you for reply.

As for me, there is no needs to use `require('./webm-encoder')` because Chrome/Mozilla/Opera have native support of vorbis/webm/ogg.

All non-native solutions are unstable and should only be used if there is no alternative. I'm searching for MediaRecorder polyfill for Edge/Safari with fallback to native methods on Chrome/Mozilla/Opera.

**Comment by ai** [comment]
> because Chrome/Mozilla/Opera have native support of vorbis/webm/ogg.

Yeap, you do not need this polyfill on Chrome/Mozilla/Opera. Just don't load polyfill for them. It will have better performance than falling back to native methods.
