### ISSUE TITLE
Cannot stop recorder on iOS

### ISSUE THREAD

**Issue by TonyBogdanov** [ai/audio-recorder-polyfill#22]
On iOS 12 calling `recorder.stop()` has no effect.

Here's my CodePen:

https://codepen.io/tonybogdanov/pen/bQXRBZ

As you can see the code will ask for a microphone, record 2 seconds then stop and report to the console. On browsers with native implementation the console looks like this:

```
"asking for mic"
"starting"
"event" "start"
"stopping"
"event" "dataavailable"
"event" "stop"
```

On polyfilled `MediaRecorder` the output is like this:

```
"asking for mic"
"starting"
"event" "start"
"stopping"
```

As you can see neither the `stop` nor `dataavailable` events are being fired. Either there's a problem with both, or the `stop()` call is not executing properly and the recorder continues.

**Comment by TonyBogdanov** [comment]
Might need a bit more digging, looks like the issue is only present on "real" devices on browserstack, but doesn't manifest on an actual physical iPhone. No idea...

**Comment by ai** [comment]
> looks like the issue is only present on "real" devices on browserstack

In this case I will think that it is browserstack issue 😛

I will reopen issue on new details
