### ISSUE TITLE
Trouble with Safari playing sound

### ISSUE THREAD

**Issue by AllanSV** [ai/audio-recorder-polyfill#24]
Hello, 

I have some trouble on Safari 11 for playing the recorded sound. 
It seems like the blob created doesn't load. 

It used to work before and now the safari player is broken. 
I first thought it has to do with my code but then I went back to your demo and there is the same bug. 

Are you aware of this problem and do you have any clues to solve it ? 

Thanks you in advance

**Comment by ai** [comment]
@AllanSV sorry for delay. I had too much work.

We have some fixes in `master` for Safari. Can you try to replace `"audio-recorder-polyfill": "^0.1.3"` to `"audio-recorder-polyfill": "ai/audio-recorder-polyfill"`, then call `npm install` (or `yarn install`), and test Safari again?

**Comment by ai** [comment]
The fix released in 0.1.4

**Comment by AllanSV** [comment]
Hi, 

I tried again, but on IOS Safari and it seems to have the same issue =/

**Comment by progfay** [comment]
I have same problem.
I added EventListener on `dataavailable` , but `event.data` was empty Blob.

**Comment by ai** [comment]
@progfay does [online demo](https://ai.github.io/audio-recorder-polyfill/) work for you?

**Comment by progfay** [comment]
Yes, online demo does not work on my iPhone.
My problem is maybe same as #4 .
The reason why it does not work was that `onaudioprocess` did not fire.

**Comment by ai** [comment]
@progfay what Safari version do you use?

**Comment by progfay** [comment]
@ai This is my iPhone's User Agent.

```
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1
```
