### ISSUE TITLE
How to enable ssl for deployment

### ISSUE THREAD

**Issue by thndrkiss** [ai/audio-recorder-polyfill#27]
Hi. I saw the demo. It is fantastic. Is there a way where I can put up a self signed ask certificate and make it working in a intranet ? Can you please guide what steps you filled to deploy in https ? Thanks

**Comment by ai** [comment]
Hi. The cheapest way to get an SSL certificate is [Let’s Encrypt](https://letsencrypt.org/). Unfortunately, it is not very easy to maintain SSL server.

So I recommend starting with some server-as-service solution, where you put a code and some company run this code on their servers with already preconfigured Let’s Encrypt.

I use GitHub Pages for audio-recorder-polyfill demo. Here are docs https://guides.github.com/features/pages/

For https://sitnik.ru I use Netlify: https://www.netlify.com/
