### ISSUE TITLE
recorded audio with polyfill has zero duration

### ISSUE THREAD

**Issue by arj-ary** [ai/audio-recorder-polyfill#32]
I am currently not able to get this work on browser safari version 12.1.2 with on High Sierra. There are no console errors but e.data has a 44 bytes audio/wav file no matter how long you record. I have the code snippet below - 

import MediaRecorder from 'audio-recorder-polyfill';

record = (stream) => {
        this.recorder = new MediaRecorder(stream);
        this.recorder.addEventListener('dataavailable', this.onRecordingReady);
}

onRecordingReady = (e) => {
        let $audioEl = this.refs.audio,
            blob = e.data, // this is a 44 bytes audio/wav
            that = this;
            $audioEl.src = URL.createObjectURL(blob);
            $audioEl.play();
        this.saveAudioFile(blob);
    }

What am i missing? Or is this something that is broken at the moment?

**Comment by ai** [comment]
I think your bug can be solved by this comment https://github.com/ai/audio-recorder-polyfill/issues/4#issuecomment-374062553

Safari allows creating Media Recorder only in the event handler.

**Comment by arj-ary** [comment]
Still doesn't work for me. I am creating Media Recorder in the event handler (see below)

navigator.mediaDevices.getUserMedia({ audio: true, video: false })
            .then(this.record);

record = (stream) => {
        this.recorder = new MediaRecorder(stream);
        this.recorder.addEventListener('dataavailable', this.onRecordingReady);
    }

**Comment by ai** [comment]
Did you try this hack? https://github.com/alecglassford/audio-recorder-polyfill/tree/working-safari-hack

That comment says that you need to change audio-recorder-polyfill and can’t be compatible with MediaRecorder API.

**Comment by arj-ary** [comment]
I have, opened their demo link in Safari - version 12.x it doesn't work. The audio just displays an error.

**Comment by ai** [comment]
What their demo? (Maybe it was my demo?)

**Comment by arj-ary** [comment]
Demo: - https://ai.github.io/audio-recorder-polyfill/
Correct, that demo link fails to play audio when opened in Safari.

**Comment by ai** [comment]
It is my demo, not the demo of their fork

**Comment by arj-ary** [comment]
Anyway, the hack that you mentioned here  https://github.com/alecglassford/audio-recorder-polyfill/tree/working-safari-hack does not work either. I tried changing the window.MediaRecorder = require('audio-recorder-polyfill')

Still doesn't work on Safari 12.x

**Comment by ai** [comment]
Sorry, I don't know how to solve it with MediaRecorder API. Use a different library.

**Comment by arj-ary** [comment]
The issue specifically with that hack is the audio file recorded is just 44 bytes and zero duration. So basically that file is empty.
