### ISSUE TITLE
iOS supported?

### ISSUE THREAD

**Issue by MrFranke** [ai/audio-recorder-polyfill#36]
Polyphill start record on ios (13), but can't play records sound after stop. What's wrong?

**Comment by ai** [comment]
I do not have iOS to test and do not develop this polyfill right now. Feel free to send PR.

**Comment by MrFranke** [comment]
Yes it's working, close issue

**Comment by slarouche-jmsl** [comment]
Yes, it's working on IPhone XS, on IPad etc but not for IPhone X.
