### ISSUE TITLE
Types for typescript

### ISSUE THREAD

**Issue by rhalaly** [ai/audio-recorder-polyfill#38]
Do you plan to support typescript? Types are missing

**Comment by ai** [comment]
This is a polyfill for standard browser API. TS should have types for that API from the box.

**Comment by rhalaly** [comment]
I'm getting this error:
> Could not find a declaration file for module 'audio-recorder-polyfill'
      Try `npm install @types/audio-recorder-polyfill` if it exists or add a new declaration (.d.ts) file containing `declare module 'audio-recorder-polyfill';`

**Comment by ai** [comment]
You should ask TS community how to deal with polyfills for existed browser API. Sorry, I am not TS expert to help you with TS issues.
