### ISSUE TITLE
Embedding recorder

### ISSUE THREAD

**Issue by neteora** [ai/audio-recorder-polyfill#39]
Hi,
I'm trying to embed a recorder in my zend project. I compiled this project by npm run build and it seems that everything is fine with that. 
I copied "as is" the compiled index.html in a my view and edited the link to embed polyfill.js.
My project is hosted by  a virtual machine (Ubuntu 18)
Chrome returns an error (getUserMedia is null). I can understand it even  I think that that could be handled better.
But if I force Polyfill it returns "Your browser doesn’t support MediaRecorder or WebRTC to be able to polyfill MediaRecorder." That is impossible.

Same answer by Safari (actually event not forcing) and Firefox, 

What am I missing ?

Thank you

**Comment by ai** [comment]
Try to create a question on StackOverflow. Sorry, I can’t help with configuring the environment for tricky cases. If you will find the exact problem, feel free to open the issue to fix docs and code.
