### ISSUE TITLE
iOS supported?

### ISSUE THREAD

**Issue by slarouche-jmsl** [ai/audio-recorder-polyfill#40]
Reference to iOS supported? #36!!

It's working on IPhone XS, IPad etc but not on IPhone X.

After the recording is stopped, not error, but the wav file it's not playing and it's invalid.

**Comment by ai** [comment]
I don't have this device. Feel free to send PR.

**Comment by floydback** [comment]
I can confirm it. It's seems a bug recently with iOS (iPhone 8). The recording is well but after recording is stopped it can't playback. If I minimize browser to tray and open after some time (~10 sec) playback is work well. Seems like iOS can't play audio when device is busy with capturing.

**Comment by floydback** [comment]
I’ve just update iOS from 13.1.3 to 13.2.3 and now all works fine.

**Comment by curt6815463** [comment]
got same issue on 13.1.3. but it works on [demo page](https://ai.github.io/audio-recorder-polyfill).
would you mind provide the source code of demo page?

**Comment by curt6815463** [comment]
i'm just trying call `navigator.mediaDevices.getUserMedia({ audio: true }).then()` on random page, only your demo page will show the red microphone icon in navbar. 🤔

**Comment by curt6815463** [comment]
i've tried call `navigator.mediaDevices.getUserMedia({ audio: true })` on random page, only your demo page would show the red microphone icon on nav bar. 

that's weird cause you are not rewrite the behavior right? (navigator.mediaDevices.getUserMedia)

**Comment by madclem** [comment]
If you are trying on mobile in develop mode (using your IP instead of localhost), you have to make sure that HTTPS is enabled. Otherwise, `navigator.mediaDevices` will be `undefined`
