### ISSUE TITLE
44bytes wav Safari 13.0.5 userAgent

### ISSUE THREAD

**Issue by amouniverso** [ai/audio-recorder-polyfill#46]
Hello,  on recent version Safari some of recordings are 44 bytes size with no audio. Aprox. 70percents of the recordings are good, 30percents - no audio. No apparent reason i can think of. Whats the problem?

**Comment by ai** [comment]
I think this thread could contain the source of the problem and a few possible solutions
https://github.com/ai/audio-recorder-polyfill/issues/4
