### ISSUE TITLE
Reference error:can't find variable h

### ISSUE THREAD

**Issue by akash-nagpure8** [ai/audio-recorder-polyfill#48]
During the process of blob creation, it is throwing the above error on Mac OS Safari Browser both in local and the online demo site.
![Image 02-03-20 at 11 47 AM](https://user-images.githubusercontent.com/61678318/75650360-a65bfa80-5c7b-11ea-9522-4d5686341fca.jpeg)

**Comment by ai** [comment]
Thanks for the report.

Fixed c008061

**Comment by ai** [comment]
The fix was released at 0.3.2

**Comment by akash-nagpure8** [comment]
Welcome.
And please check for chrome and Firefox also.It was also not running both the browser.

**Comment by ai** [comment]
It was a browser non-related issue.

In the recent 1.0, we moved to ES2016 syntax and one tricky syntax construction was not supported well by UglifyJS. I moved back to ES5 `for (let i = 0; i < buffer.length; i++)` syntax there and bug was fixed.

**Comment by akash-nagpure8** [comment]
Thanks for fixing the issue and quick response.
