### ISSUE TITLE
Issue with createWorker function

### ISSUE THREAD

**Issue by kaYcee** [ai/audio-recorder-polyfill#49]
When using the latest version 0.3.2 of this (great!) lib, I receive the following error:
`Uncaught SyntaxError: Unexpected end of input`

I narrowed it down to the createWorker function, which removes the trailing brace "}" for some reason:

> let js = fn
>     .toString()
>     .replace(/^function\s*\(\)\s*{/, '')
>     .replace(/}$/, '')

Even when adding back the brace, other issues pop up. Up to and including version 0.2.0 everything worked fine, so the issues must have been introduced with version 0.3.0.

**Comment by ai** [comment]
Thanks for the report. It could be a result of our migration to ES modules.

I will try to fix it today.

**Comment by ai** [comment]
Fixed a906e7d

**Comment by ai** [comment]
Released in 0.3.3

**Comment by kaYcee** [comment]
Great, thanks for your quick action!
