### ISSUE TITLE
Invalid blobs on 13.0.5

### ISSUE THREAD

**Issue by GiteZz** [ai/audio-recorder-polyfill#52]
Spec:

- Safari 13.0.5
- macOS 10.15.3

When I tried the default code on the readme the data in the 'dataavailable' returns invalid data. When looking at these blobs the event only returns two distinct file size: 44B and 4140B. The 44B bit file gives an error in the player while the 4140B file is able to be played but contains no sound. 

In order to investigate the issue I looked at the https://ai.github.io/audio-recorder-polyfill/ example but that gave exactly the same results (2 diff files size, both containing no useful information). I looked at the https://github.com/ai/audio-recorder-polyfill/issues/4 discussion and tried to reboot my pc. This allowed me to get one recording but all recordings after that failed again. I rebooted again but then it gave me directly an 44B file.

If you need further investigating from my side please send.

**Comment by ai** [comment]
New Safari supports MediaRecorder. This is why I will not support this project.

But I will accept and release PR.

**Comment by GiteZz** [comment]
Oké I can understand that the project won't be updated. I will have to look for a different solution since Safari 13 only allows MediaRecorder support via experimental features and I can't ask to enable experimental features.
