### ISSUE TITLE
Built version including mp3 encoding

### ISSUE THREAD

**Issue by madeInLagny** [ai/audio-recorder-polyfill#55]
Hi, I develop using a buildless environment. How can I get a built version of the polyfill to include to my project ? Tried to build the repo but failed on node-env
Thanks

**Comment by ai** [comment]
We do not support buildless environment because I think they are bad for user performance

**Comment by madeInLagny** [comment]
Sure, but this is just for development purposes. I don't think that the cdn
option gives access to mp3 encoding...or does it ?

Le mar. 28 avr. 2020 à 18:54, Andrey Sitnik <notifications@github.com> a
écrit :

**Comment by ai** [comment]
We do not have a CDN option right now. You need to build the library to use it. Even if you use default WAVE encoder.

**Comment by madeInLagny** [comment]
Okay, thanks. I built the library. I suppose that I need to import
test/demo/build/build.js to use it ? How do I import mpeg-encoder in my
built version ?

Le mar. 28 avr. 2020 à 20:20, Andrey Sitnik <notifications@github.com> a
écrit :

**Comment by ai** [comment]
Here is the code example
https://github.com/ai/audio-recorder-polyfill/blob/master/README.md#mp3
