### ISSUE TITLE
Add documentation on how to build library and use it

### ISSUE THREAD

**Issue by madeInLagny** [ai/audio-recorder-polyfill#56]
During development phase, I need to use a built version of the polyfill. I ran 'npm run start' and a /test/demo/build directory was created. 
I added <script src="/audio-recorder-polyfill-master/test/demo/build/polyfill.js"></script> in index.html.

How do I access the library ? In particular I want to compress files in mp3. I am not sure how to use 
`https://github.com/ai/audio-recorder-polyfill#mp3` with the built library.

**Comment by ai** [comment]
You need to use some bundler on *your project*. I recommend using [Parcel](https://parceljs.org/). It is easy to use and has great DX. webpack is another popular option.

In your project with bundler, you need just to use `require()` function, which will be tracked by Parcel, and then many separated files will be converted to the single file of bundled JS.

Loading each library as a separate JS file (or from CDN) is very bad for performance.

**Comment by madeInLagny** [comment]
Thank you for your explanations. I will proceed with adding your polyfill
to my bundle (I use rollup). Great piece of work !

Le ven. 1 mai 2020 à 15:26, Andrey Sitnik <notifications@github.com> a
écrit :
