### ISSUE TITLE
Request for more detailed installation

### ISSUE THREAD

**Issue by rumus007** [ai/audio-recorder-polyfill#57]
The documentation provided seems to be inadequate for beginners. Request for a more detailed installation process. 
Thanks

**Comment by ai** [comment]
On what step did you find a problem?

**Comment by rumus007** [comment]
i was able to start and stop recording as the browser shows the sign that the site is using my microphone but I cannot get hold of the audio once it is stopped. 

Im using laravel and vue js for the javascript part


![Screenshot from 2020-06-04 11-12-48](https://user-images.githubusercontent.com/51116139/83718266-721a2080-a654-11ea-9f73-ad4bdd222297.png)

**Comment by ai** [comment]
You should use `MediaRecorder` docs. You installed polyfill correctly.
