### ISSUE TITLE
sampleRate

### ISSUE THREAD

**Issue by wilsondonizetti** [ai/audio-recorder-polyfill#58]
Hi! Good evening.

How configure sampleRate? or options of the MediaRecorder base.
I need reduce size of the audios.
{
   audioBitsPerSecond : 8000
   bitsPerSecond: 8000
}
Thanks!

**Comment by ai** [comment]
I recommend to use MP3 to reduce the size.

I think we do not have a solution for WAV.

**Comment by wilsondonizetti** [comment]
Thanks! work for me.

**Comment by wangning08115** [comment]
How to use MP3 to reduce the size? I am starter, Can you help me?
