### ISSUE TITLE
How to know the AudioContext.currentTime when recording started

### ISSUE THREAD

**Issue by hector** [ai/audio-recorder-polyfill#61]
When `mediaRecorder.start()` is called some time can pass until it really records the first sample coming from a media device. Is there a way to know this first sample position in time? Maybe using the AudioContext clock (AudioContext.currentTime).

I need this because I record my voice while reproducing some music and I need to sync it perfectly afterwards.

**Comment by ai** [comment]
Sorry. Have no idea.

**Comment by hector** [comment]
I think this could be known inside the ScriptProcessor, when you receive the first buffer.
But if I am correct, when the ScriptProcessor receives the buffer you don't know how "old" is it, right?
