### ISSUE TITLE
this.requestData is not a function

### ISSUE THREAD

**Issue by leifniem** [ai/audio-recorder-polyfill#64]
I received this error when terminating the recording with a timer and can absolutely not figure out why it appears.

The error references https://github.com/ai/audio-recorder-polyfill/blob/master/index.js#L133 as the source of the issue, but since the class clearly has a method of that name i'm a bit lost on why the error gets thrown.

Sorry if i'm not seeing the clear issue here.

I'm using the suggested polyfill implementation given in the README with Webpack.

Thank you for your help :)

**Comment by leifniem** [comment]
Use of the polyfill can be found here: https://github.com/leifniem/Vue-Audio-Survey/blob/master/src/js/recorderMixin.js

**Comment by ai** [comment]
This diff will fix the problem:

```diff
- setTimeout(this.$_recorder.stop, maxTakeLength)
+ setTimeout(() => this.$_recorder.stop(), maxTakeLength)
```

The passing method to `setTimeout` (or any other function with callbacks) will detach `this` in this method.

**Comment by leifniem** [comment]
Thank you very very much!

Sorry for raising this as an issue 😅
