### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by pmbednarczyk** [ai/audio-recorder-polyfill#68]
Any chance it would also record video type streams? :)

**Comment by ai** [comment]
Nope. We try to focus on small task to have a small size.

Anyway, Safari is adding MediaRecorder support.

**Comment by baishusama** [comment]
@ai If I understand it right, without considering being a small size, it is possible to do a "video-recorder-polyfill" ？

**Comment by ai** [comment]
@baishusama I didn’t investigate this question to be sure
