### ISSUE TITLE
Not working on iOS Safari

### ISSUE THREAD

**Issue by mycaigou** [ai/audio-recorder-polyfill#86]
ios: 14.0

Looking forward to your reply~

![b9eb8f28-868d-4f45-ae17-e4224bf6ac29](https://user-images.githubusercontent.com/58027952/106690766-55801f00-660d-11eb-8261-f7c913a2f351.jpg)
![image](https://user-images.githubusercontent.com/58027952/106690865-7ba5bf00-660d-11eb-84fb-b00eedaef7eb.png)

**Comment by ai** [comment]
Please check other closed issues. It is not so easy to use it in Safari.

**Comment by victorykong** [comment]
You mean the library still doesn't support iOS Safari?

**Comment by ai** [comment]
Supports, but there are some limits.

It is important to start recording directly in the `click` event listener (not in `setTimeout` or after any `Promise`).

Unfortunately, I do not support this project anymore. You need to investigate it by your own
