### ISSUE TITLE
Stop event never dispatched

### ISSUE THREAD

**Issue by e8johan** [ai/audio-recorder-polyfill#87]
Looking at the code for the stop function, i.e. https://github.com/ai/audio-recorder-polyfill/blob/main/index.js#L121, it seems that the stop event never is dispatched, only the error if stopping an inactive stream. Something like this would probably do the trick:

```
return this.em.dispatchEvent(new Event('stop'))
```

**Comment by ai** [comment]
it is not an event, but an error https://github.com/ai/audio-recorder-polyfill/blob/main/index.js#L15

**Comment by e8johan** [comment]
Yes, I know that what is currently dispatched is the error. I expected a stop event to be dispatched as well, e.g. https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/onstop . This is currently not dispatched for me, meaning that my logic for uploading the resulting audio blob never gets called.

**Comment by e8johan** [comment]
Hmm... found it here: https://github.com/ai/audio-recorder-polyfill/blob/main/index.js#L56

So, I guess I need to do a bit more debugging on my side...
