### ISSUE TITLE
Using chunked recording only yields header with duration of the first blob. 

### ISSUE THREAD

**Issue by fosteman** [ai/audio-recorder-polyfill#95]
Using chunked recording only yields header with duration of the first blob.

**Comment by ai** [comment]
Yeap. This is a limit of WAV format.

If you know any solution, please send PR.

**Comment by fosteman** [comment]
Hm. Is this is a limitation of this polyfill though ? Or, in other words, is there another encoder \ file format \ mimeType I should use in instantiating a recorder to beat this issue ? 
What do you know of other ways of addressing this ? Is there a package to rewrite the .wav's header ? Is there a way to ffmpeg all blobs together ?
 Is there a way to post-process composed media file to get the right duration ?

**Comment by fosteman** [comment]
Hm. @ai, if I may ask some questions regarding this. I've traversed a lot of google, but I wonder what I could learn from you more.

Is this is a limitation of this polyfill though ? Or, in other words, is there another encoder \ file format \ mimeType I should use in instantiating a recorder to beat this issue ?
What do you know of other ways of addressing this ? Is there a way to post-process composed media file to get the right duration ? Is there a package to rewrite the .wav's header ? Is there a way to ffmpeg all blobs together ?

**Comment by ai** [comment]
There are 2 options:

1. Change encoding (for instance to MP3)
2. Post-process files on the server

> Is there a package to rewrite the .wav's header ?

It is very simple format. Read any docs and you can write it on your own.
